version: '2'
services:
  guideline-server:
    build:
      context: .
      dockerfile: apps/guideline-server/Dockerfile
    ports:
      - "5000:80"
  viz-backend:
    build:
      context: .
      dockerfile: apps/viz-backend/Dockerfile
    ports:
      - "5001:80"
  patientdata-server:
    build:
      context: .
      dockerfile: apps/patientdata-server/Dockerfile
    ports:
      - "5002:80"
