version: '2'
services:
  guideline-server:
    build:
      context: .
      dockerfile: apps/guideline-server/Dockerfile
    ports:
      - "5001:80"
  viz-backend:
    build:
      context: .
      dockerfile: apps/viz-backend/Dockerfile
    ports:
      - "5002:80"
    volumes:
      - comparator-results:/var/data
  patientdata-server:
    build:
      context: .
      dockerfile: apps/patientdata-server/Dockerfile
    ports:
      - "5003:80"
  comparator:
    build:
      context: .
      dockerfile: apps/comparator/Dockerfile
    ports:
      - "5004:80"
    volumes:
      - comparator-results:/var/datavizuguidiz
#  viz:
#    build:
#      context: .
#      dockerfile: apps/viz/Dockerfile
#    ports:
#      - "5000:3838"

volumes:
  comparator-results:
