version: "3.7"
services:
  guideline-interface:
    build:
      context: apps/guideline_interface/
    ports:
      - "5001:80"
  ui-backend:
    build:
      context: apps/ui_backend
    ports:
      - "5002:80"
    volumes:
      - comparator-results:/var/data
  clinical-data-interface:
    build:
      context: apps/clinical_data_interface
    ports:
      - "5003:80"
  adherence-evaluator:
    build:
      context: apps/adherence_evaluator
    ports:
      - "5004:80"
    volumes:
      - comparator-results:/var/data
  ui:
    build:
      context: apps/ui
    ports:
      - "5000:3838"

volumes:
  comparator-results:
