name: Validate JSONs

on: [pull_request]

jobs:
  validate_configurations:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate FHIR schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./FHIR/fhir.schema.json
          json_path_pattern: FHIR/.*\.fhir\.json$
